In [1]:
import numpy as np

In [2]:
np.random.seed(0)

In [3]:
x1=np.random.randint(10,size=6)

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x2=np.random.randint(18,size=(3,4))

In [6]:
x2

array([[ 4,  6, 12,  1],
       [ 6,  7, 14, 17],
       [ 5, 13,  8,  9]])

In [7]:
x3=np.random.randint(10,size=(3,4,5))

In [8]:
x3

array([[[4, 3, 0, 3, 5],
        [0, 2, 3, 8, 1],
        [3, 3, 3, 7, 0],
        [1, 9, 9, 0, 4]],

       [[7, 3, 2, 7, 2],
        [0, 0, 4, 5, 5],
        [6, 8, 4, 1, 4],
        [9, 8, 1, 1, 7]],

       [[9, 9, 3, 6, 7],
        [2, 0, 3, 5, 9],
        [4, 4, 6, 4, 4],
        [3, 4, 4, 8, 4]]])

In [9]:
print("x3 ndim",x3.ndim)
print("x3 shape",x3.shape)
print("x3 size",x3.size)


x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [10]:
x1.dtype

dtype('int32')

In [11]:
x2.dtype

dtype('int32')

In [12]:
x3.dtype

dtype('int32')

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [14]:
x1[0]

5

In [15]:
x1[4]

7

In [16]:
x1[-1]

9

In [17]:
x1[-2]

7

In [18]:
x2

array([[ 4,  6, 12,  1],
       [ 6,  7, 14, 17],
       [ 5, 13,  8,  9]])

In [19]:
x2[0][0]

4

In [20]:
x2[2][0]

5

In [21]:
x2[2][-1]

9

In [22]:
x=np.arange(10)

In [23]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[:5] # first five elements


array([0, 1, 2, 3, 4])

In [25]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]

array([4, 5, 6])

In [27]:
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
x[1::2]

array([1, 3, 5, 7, 9])

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2]

array([5, 3, 1])

In [31]:
x2[:2,:3]

array([[ 4,  6, 12],
       [ 6,  7, 14]])

In [32]:
x2[:3,::2]

array([[ 4, 12],
       [ 6, 14],
       [ 5,  8]])

In [33]:
x2[::1,::-1]

array([[ 1, 12,  6,  4],
       [17, 14,  7,  6],
       [ 9,  8, 13,  5]])

In [38]:
print(x2[:,0])

[3 7 1]
