In [2]:
import numpy as np
a=np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
L=range(1000)
%timeit[i**2 for i in L]

409 µs ± 2.75 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a=np.arange(1000)
%timeit a**2    

1.97 µs ± 69 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [7]:
print(a.ndim)

1


In [9]:
a.shape

(4,)

In [10]:
len(a)

4

In [11]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [20]:
len(b) 

2

In [21]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
c.ndim

3

In [23]:
c.shape #return a tupule

(2, 2, 2)

In [25]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [26]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [33]:
b=np.diag([1,2,3,4])
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [3]:
import numpy as np
a=np.random.rand(20)
a

array([0.11507908, 0.08958271, 0.24032324, 0.43688358, 0.13502424,
       0.60813679, 0.78936381, 0.43531199, 0.86353213, 0.44417409,
       0.66061533, 0.49330098, 0.86466163, 0.24252368, 0.14543267,
       0.02761481, 0.62891312, 0.17574943, 0.96246828, 0.22114882])

In [35]:
a=np.random.randn(4)
a

array([-0.29802936,  0.6838362 ,  0.16715834,  1.22587542])

In [5]:
a=np.arange(10)
print(a.dtype)
print(a)

int32
[0 1 2 3 4 5 6 7 8 9]


In [37]:
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
d=np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [40]:
b=np.array([True,False,True,True])
print(b.dtype)

bool


In [41]:
s=np.array(['Ram','Seetha'])
s.dtype

dtype('<U6')

In [43]:
a=np.arange(10)
print(a[5])

5


In [44]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [45]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [46]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
a[1:8:2]    #without including the 8th element

array([1, 3, 5, 7])

In [6]:
b=np.arange(5)
a[5:]=b[ : : -1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [52]:
a=np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
b=a[::2]
b

array([ 0,  2,  4,  6,  8, 10])

In [54]:
np.shares_memory(a,b)

True

In [55]:
b[0]=10
b

array([10,  2,  4,  6,  8, 10])

In [56]:
a #because they share the same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
a=np.arange(10)
c=a[::2].copy() #force a copy
c

array([0, 2, 4, 6, 8])

In [59]:
np.shares_memory(a,c)

False

In [60]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a=np.random.randint(0,20,15)
a  

array([12, 14,  5,  6, 16,  2,  3, 14,  8,  5,  7,  3, 10,  2,  1])

In [63]:
mask=(a%2==0)

In [64]:
extract_from_a=a[mask]
extract_from_a

array([12, 14,  6, 16,  2, 14,  8, 10,  2])

In [65]:
a[mask]=-1

In [66]:
a

array([-1, -1,  5, -1, -1, -1,  3, -1, -1,  5,  7,  3, -1, -1,  1])

In [68]:
a=np.arange(0,100,10)
a
    

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
a[[1,2,3,4,5,6,7]]

array([10, 20, 30, 40, 50, 60, 70])

In [71]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [11]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [12]:
b=a**2
b

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
b=np.ones(4)+1
a=(a-b).copy()
a

In [15]:
a

array([-1.,  0.,  1.,  2.])

In [16]:
b

array([2., 2., 2., 2.])

In [17]:
a*b

array([-2.,  0.,  2.,  4.])

In [19]:
c=np.diag([1,2,3,4])
print(c*c)
print("***************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [81]:
a=np.array([1,2,3,4])
b=np.array([2,2,3,4])
a==b #element-wise

array([False,  True,  True,  True])

In [82]:
a>b

array([False, False, False, False])

In [83]:
a<b

array([ True, False, False, False])

In [84]:
np.array_equal(a,b)

False

In [85]:
np.array_equal(a,c)

False

In [86]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [87]:
np.logical_and(a,b)

array([ True,  True,  True,  True])

In [88]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.log(a)

C:\Users\anjineyulu\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [90]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [92]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [93]:
x.sum(axis=0)   #column wise

array([3, 3])

In [97]:
x.sum(axis=1)    #row wise

array([2, 4])

In [98]:
x=np.array([1,3,2])
x.min()

1

In [99]:
x.max()

3

In [100]:
x.argmin() #returns the index

0

In [101]:
x.argmax()

1

In [102]:
np.all([True,False])

False

In [103]:
np.any([True,False])

True

In [107]:
a=np.ones([50,50])
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [109]:
np.any(a=1)

True

In [110]:
np.all(a==a)

True

In [1]:
import numpy
a=numpy.array([1,2,3,4])
b=a.T
c = numpy.array([a])
d = c.T
print(a.shape)
print(b.shape)
print(b)#Here it didn't transpose because 'a' is 1 dimensiona
print(c.shape)
print(d.shape)  
print(d)#Here it did transpose because a is 2 dimensional

(4,)
(4,)
[1 2 3 4]
(1, 4)
(4, 1)
[[1]
 [2]
 [3]
 [4]]


In [4]:
import numpy as np
a = np.arange(12).reshape(3,4)
i = np.array([[0,1],[1,2]])
j = np.array([[2,1],[3,3]])

print(a[i,j])

[[ 2  5]
 [ 7 11]]


In [6]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[1,2,3]])
a+b

array([[2, 4, 6],
       [2, 4, 6]])

In [7]:
b=np.array([[[ 1, 2],
[ 3, 4]],

[[ 5, 6],
[ 7, 8]],

[[ 9, 10],
[11, 12]],

[[13, 14],
[15, 16]],

[[17, 18],
[19, 20]]])
b.sum(axis=0)

array([[45, 50],
       [55, 60]])

In [20]:
a=np.array([[[1,2,3],[6,7,8],[1,1,1],[2,2,2]],[[1,2,3],[6,7,8],[1,1,1],[2,2,2]]])
print(a)
print(np.shape(a))
print(np.ndim(a))
print(a.sum(axis=0)) #axis=0 Col wise sum
print(a.sum(axis=1)) #axis=1 Row wise sum
print(a.sum(axis=2)) #axis=2 third dim wise sum

[[[1 2 3]
  [6 7 8]
  [1 1 1]
  [2 2 2]]

 [[1 2 3]
  [6 7 8]
  [1 1 1]
  [2 2 2]]]
(2, 4, 3)
3
[[ 2  4  6]
 [12 14 16]
 [ 2  2  2]
 [ 4  4  4]]
[[10 12 14]
 [10 12 14]]
[[ 6 21  3  6]
 [ 6 21  3  6]]


In [11]:
b=np.array([[1,2,3],[6,7,8],[1,1,1],[2,2,2]])
print(b)

[[1 2 3]
 [6 7 8]
 [1 1 1]
 [2 2 2]]


In [12]:
b.shape

(4, 3)

In [13]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

In [16]:
x1_new = x1[:, np.newaxis]
print(x1_new)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [17]:
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [18]:
x2_new = x2[:, np.newaxis]

In [19]:
x2_new

array([[5],
       [4],
       [3]])

In [20]:
x1 + x2_new

array([[ 6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8]])

In [22]:
arr=np.arange(5*5).reshape(5,5)

In [23]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr_5D = arr[np.newaxis,np.newaxis,np.newaxis, np.newaxis, np.newaxis]

In [25]:
arr_5D.shape

(1, 1, 1, 1, 1, 5, 5)

In [26]:
print(arr_5D)

[[[[[[[ 0  1  2  3  4]
      [ 5  6  7  8  9]
      [10 11 12 13 14]
      [15 16 17 18 19]
      [20 21 22 23 24]]]]]]]


In [ ]:
a=1